##
## ------------------------------
## |   M E D I A  G O N E I X   |
## ------------------------------
##
version: '3.5'
services:
  # ----------------------------------------
  # DELUGEVPN
  # ----------------------------------------
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '8112:8112'
        - '8118:8118'
        - '58846:58846'
        - '58946:58946'
    cap_add:
        - NET_ADMIN
    environment:
        - VPN_ENABLED=yes
        - VPN_USER= # username of your VPN account for your provider
        - VPN_PASS= # password of your VPN account for your provider
        #- VPN_REMOTE=${VPN_REMOTE} # select your file .ovpn
        - VPN_PORT=1198
        - VPN_PROTOCOL=udp
        - VPN_DEVICE_TYPE=tun
        - VPN_PROV=custom
        - STRONG_CERTS=no
        - ENABLE_PRIVOXY=yes
        - STRICT_PORT_FORWARD=yes
        #- LAN_NETWORK=${CIDR_ADDRESS}
        - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
        - DEBUG=false
        - PUID=1000
        - PGID=1000
    volumes:
        #- '${DLDIR}:/data'
        - './delugevpn/config:/config'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # JACKETT
  # ----------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '9117:9117'
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - './jackett:/config'
        #- '${DLDIR}/completed:/downloads'
        - '/etc/localtime:/etc/localtime:ro'
 
  # ----------------------------------------
  # NETDATA
  # ----------------------------------------
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    hostname: 'mediacenter'
    ports:
        - '19999:19999'
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    # environment:
    #     - NETDATA_CLAIM_TOKEN=''
    #     - NETDATA_CLAIM_URL=https://app.netdata.cloud
    #     - NETDATA_CLAIM_ROOMS=''
        
  # ----------------------------------------
  # PLEX
  # ----------------------------------------
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '32400:32400/tcp'
        - '3005:3005/tcp'
        - '8324:8324/tcp'
        - '32469:32469/tcp'
        - '1900:1900/udp'
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    environment:
        - PLEX_CLAIM=''
        - ADVERTISE_IP=http://32400/
        - PLEX_UID=1000
        - PLEX_GID=1000
    hostname: mediacenter
    volumes:
        - './plex:/config'
        - './plex/transcode:/transcode'
        #- '${MISCDIR}:/data/misc'
        #- '${MOVIEDIR}:/data/movies'
        #- '${MUSICDIR}:/data/music'
        #- '${TVDIR}:/data/tvshows'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # PORTAINER
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '9000:9000'
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - './portainer:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/localtime:/etc/localtime:ro'
    command: -H unix:///var/run/docker.sock

  # ----------------------------------------
  # RADARR
  # ----------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '7878:7878'
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - './radarr:/config'
        #- '${DLDIR}/completed:/data/completed'
        #- '${MOVIEDIR}:/movies'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # SONARR
  # ----------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '8989:8989'
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
    volumes:
        - './sonarr:/config'
        #- '${DLDIR}/completed:/data/completed'
        #- '${TVDIR}:/tv'
        - '/etc/localtime:/etc/localtime:ro'
  # ----------------------------------------
  # WATCHTOWER
  # ----------------------------------------
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: "bridge"
    hostname: 'mediacenter'
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_SCHEDULE=0 0 */4 * * *
        - WATCHTOWER_INCLUDE_STOPPED=true
        - TZ=Europe/Paris
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
